version: '3.6'

services: 
    db:
        image: mysql
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: lucky
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        ports:
          - '3306:3306'
        volumes: 
            - ./init:/docker-entrypoint-initdb.d